### ISSUE TITLE
Add ability to scale applications

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#106]
Add the ability to manage the scaling of applications that have been configured for this capability. 

Initial thought is to add scaling options on the Application List page (along with start/stop/restart/delete application)

**Comment by ron-murhammer** [comment]
Initial implementation: https://github.com/OpenShiftMobile/openshift-mobile/pull/110

**Comment by ron-murhammer** [comment]
Closing this since the pull request has been merged.
