### ISSUE TITLE
Dynamic generation of Navigation tabs and dropdown lists at runtime

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#111]
Due to limitations in the JQuery Mobile framework and to facilitate complex actions within the application,  certain components should by dynamically generated at runtime.

**Initial Use Cases:**
- Navigation Tabs
- Dropdown options on listviews

Based on the specific implementation, items can be displayed or hidden

**Comment by ron-murhammer** [comment]
Hey Andy,

Are there any other navigation/dropdown lists that you'd like to be dynamic besides the scaling options?

I'd say its probably better to just merge the pull request for #110 and we can work on any dynamic menu enhancements separately in this issue.

**Comment by sabre1041** [comment]
Closing as no effort will continue on the OSE 2x side

**Comment by sabre1041** [comment]
Closing as no effort will continue on the OSE 2x side

**Comment by sabre1041** [comment]
Closing as no effort will continue on the OSE 2x side
