### ISSUE TITLE
titlebar overlaps and obscures buttons

### ISSUE THREAD

**Issue by eddo888** [openshift-mobile/openshift-mobile#124]
![](http://i.imgur.com/qyltIa9.jpg)

**Comment by eddo888** [comment]
iphone 5s with iOS 7.1.1

**Comment by jyore** [comment]
Thanks for the report, we have noticed this too and should have a fix in the next release that should be coming out next month.

@rhoads-zach , can you please take a look at this? I believe you had been working on it previously

**Comment by sabre1041** [comment]
The following is a snippet from the osm-enterprise-support branch containing the fix to index.html

``` JavaScript
            $(document).bind('osm-ready',function() {
                var settings = app.settings.load();

                $.mobile.changePage('#login-page',{transition:DEFAULT_TRANSITION});
                populateLoginForm(settings);


                // IOS Navbar Fix
                var updateStatusBar = navigator.userAgent.match(/iphone|ipad|ipod/i) &&
                    parseInt(navigator.appVersion.match(/OS (\d)/)[1], 10) >= 7;
                if (updateStatusBar) {
                    document.body.style.webkitTransform = 'translate3d(0, 20px, 0)';
                }

                if(settings.autolog) {
                    loginToggleDisableFields();
                    login(app,loginSuccess,loginFail);
                }
                $('[data-role="navbar"] a:first').click();

            });
```

**Comment by jyore** [comment]
Added a fix in a pull request. @sabre1041 can you please take a look?

Additionally, since this is modifications to the phonegap browser behavior, it should go in the onDeviceReady deferred (as in the PR I submitted)
