### ISSUE TITLE
Application Operations

### ISSUE THREAD

**Issue by jyore** [openshift-mobile/openshift-mobile#14]
From the Application Menu, the menu events need to be bound

Basic Operations
- Start
- Stop
- Restart
- Delete

Advanced Operations
- Tidy
- Scale Up/Down

**Comment by sabre1041** [comment]
Start/Stop/Restart/Delete have been implemented

**Comment by jyore** [comment]
Closing as the basic operations have been implemented. The advanced features should move to their own ticket.
