### ISSUE TITLE
Document Rest API Version

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#21]
Document the variations between the OpenShift rest API version. The range of supported API versions for release 1 will be the currently supported OpenShift Enterprise version (1.4) and the current implementation in OpenShift Online (1.6)

**Comment by jyore** [comment]
Working on documenting the changes from 1.4->1.5->1.6

Ideally, there will be an mapping function that will take the results from any version call and produce an object with normalized key-value pairs.  This way the builder functions can remain the virtually the same and support all versions.  Anything that is added in new versions should produce 'undefined' information in the older version objects and the builder methods should ignore adding those features

references #4

**Comment by jyore** [comment]
Based on the completion of #4, I can work on formally writing up key information used in REST commands, page content, and app features

**Comment by ron-murhammer** [comment]
Hey Joey have you made any progress on this? I'm starting to work on the user management stuff and could probably benefit from whatever information you have so I don't have to comb through the current code and OpenShift REST docs as much.

**Comment by jyore** [comment]
I haven't gotten too much on it unfortunately. The OSM_Support function has
the rest path code if you need examples. I had an xcel doc I think in the
/doc directory that I started to put in the differences in versions for
some of the calls.

**Comment by sabre1041** [comment]
Closing as no effort will continue on the OSE 2x side
