### ISSUE TITLE
Create Documentation on Setting up Developer Environment

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#36]
Create documentation to describe the process of installing and configuring a developer machine to develop OpenShift Mobile
- List required software
- Document supported operating systems
- List any best practices, tip, quirks
- Provide step by step details to ensure steps can be easily followed by all levels of developers

**Comment by ron-murhammer** [comment]
Added developer setup guide to wiki: https://github.com/sabre1041/openshift-mobile/wiki/Getting-Started

**Comment by jyore** [comment]
Looks good. Going to close the ticket. We can reopen or open a new ticket if there needs to be additions or changes
