### ISSUE TITLE
Build API Version Support

### ISSUE THREAD

**Issue by jyore** [openshift-mobile/openshift-mobile#4]
The API should intelligently determine what calls to make based on the specified API version

**Comment by sabre1041** [comment]
In addition, this issue should also take into effect which properties of the retrieved entity relate to the desired information

Example:

Name of Domain:

v4 = domain.id
v6 = domain.name

**Comment by jyore** [comment]
blocked by #21

**Comment by jyore** [comment]
this ticket should take priority and will, unfortunately, require some rework of the entire app framework.

At login, the response should contain the list of available API versions. We should select the 'latest' version by default, but perhaps add an override option in some user settings.

The framework should do three things in terms of API version:

**1) Account for any differences in responses that map to same/similar values**
    An example is noted above where the name of the domain in earlier versions was `domain.id` and in later versions is `domain.name`

**2) Determine how to format REST calls, as they change based on version**
    An example is that in earlier versions, the REST calls were done by name while in later versions that name has been hashed into a key that should be used.

**3) enable/disable content based on what operations are available in the selected version API.**
    An example of this would be once OSM supports the recently added OpenShift Environment Variables, then the later versions would need to setup options to manage those environment variables. However, if earlier versions are being used (especially possible in the Enterprise world), then the Environment Variable content should either be disabled or probably not even shown in the UI.

**Comment by jyore** [comment]
Making progress on this. Still a lot of work to do. I am also cleaning up all of the underlying code to support this new model.

Ideally, all operations will check through the OSM_Version (not in current code base, added in future commit) object instance (will build compatibility after login) to verify that the page in the app can support all operations. When pages are constructed, elements will be inserted or hidden based on compatibility report.

**Comment by jyore** [comment]
Making much progress...hopefully will be done today

**Comment by jyore** [comment]
Solution provided in pull request #55

**Comment by jyore** [comment]
Pull request #55 was accepted which fixes this issue. closing
