### ISSUE TITLE
Create Functional Testing Scenarios

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#42]
To properly test the OpenShift Mobile application, create scenarios that would fully test the functionality of the application
- Review functionality of OpenShift Mobile Application
- Create and document scenarios for which other developers in a testing role can perform
- Research any additional tools which could be leveraged to aid in the testing process

**Comment by ghost** [comment]
is there a certain location that we would document these scenarios?  And is there a certain format that we want to follow

**Comment by ghost** [comment]
Created initial listing on new wiki page under Testing Scenarios:
https://github.com/sabre1041/openshift-mobile/wiki/Testing-Scenarios

**Comment by jyore** [comment]
That location works. 
Format is up to you since one does not presently exist.

**Comment by sabre1041** [comment]
Closing as no effort will continue on the OSE 2x side
