### ISSUE TITLE
Create User Management Section

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#45]
To provide functionality to manage the settings for a given Users' OpenShift account, a new section within the application should be created to allow for the management of a user account. This high level task should be broken down into sub tasks as it contains many components. 

The following features should be included in this section:
- Display core User information
  - Login Name
  - Gear Details - Consumed/Max Available
  - Ability to create subaccounts
  - List parent/child accouts
- Subscription Management
  - List active subscription
  - List available subscription
  - Changing subscription plan
- SSH Key Management
  - CRUD (list, add, update, delete)

**Comment by ron-murhammer** [comment]
Created pull request to add settings page with tabs for user info, subscriptions, and SSH keys (all read-only): https://github.com/OpenShiftMobile/openshift-mobile/pull/79

**Comment by ron-murhammer** [comment]
TODO
- Show which subscription is active (check mark) and a link openshift subscription page
- Allow SSH key delete
- Show only first 8 and last 8 of SSH key

**Comment by sabre1041** [comment]
@ron-murhammer, is there any functionality outstanding that needs to be completed prior to v1?

**Comment by ron-murhammer** [comment]
Not that I'm aware of. Please test it and make sure everything works as you expect.

**Comment by sabre1041** [comment]
Tested Settings section. Able to view user details, available subscription plans with current plan selected and associated SSH keys. Confirmed delete functionality of preexisting SSH key.
