### ISSUE TITLE
Investigate feasibility of leveraging SSH

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#47]
Many of the features exposed through the OpenShift RHC tool leverage SSH to communicate between the client and OpenShift platform. Having the ability to remotely connect to an OpenShift gear would expand the possibilities of the OpenShift Mobile application

Example uses:
- Viewing application logs

**Comment by ghost** [comment]
Would we want to use this to directly SSH into an application? (e.g. ssh user@application) Or would we want to expose different operations that would use ssh to communicate with the application for us? (e.g. ssh 'cat /location/of/logs/logfile' and display it in a buffer locally)

**Comment by sabre1041** [comment]
Providing the ability to view the most recent content of an applications' log was my initial goal for this initiative. Handling a persistent  ssh session does not seem as feasible for a mobile application

**Comment by ptforsberg** [comment]
I would recommend using an external client like Juice SSH client for this.

**Comment by sabre1041** [comment]
Closing as no effort will continue on the OSE 2x side
