### ISSUE TITLE
Create Android App Store Workflow

### ISSUE THREAD

**Issue by ron-murhammer** [openshift-mobile/openshift-mobile#48]
- Research requirements to add application to Android App Store (Amazon vs Google Play)
- Register test and production accounts with respective application store
- Document deployment process

**Comment by ron-murhammer** [comment]
Next steps for Android distribution:
- Register for a Google Play Developer account (https://play.google.com/apps/publish/signup/) and/or Amazon App Developer account (https://developer.amazon.com/public/)
- Google Play requires $25 fee but Amazon App is free

**Comment by ron-murhammer** [comment]
- Created a Amazon App Developer account and added an OpenShift Mobile app: https://developer.amazon.com/application/general/M1YPY3WXEQ3JET/detail.html

Things needed to submit to Amazon App store:
- Descriptions and product bullet points
- Icons and screenshots
- Decide when we are ready to submit an initial version

General process strategies we need to discuss:
- Release to Amazon App store or Google Play?
- Can we expense the Google Play fee? In general, can we expense OpenShift Mobile related expenses?

**Comment by sabre1041** [comment]
Created Google Play account and added members of core team to https://play.google.com/apps/publish

**Comment by ron-murhammer** [comment]
Created OpenShift Mobile app under our Google Play account: https://play.google.com/apps/publish/?dev_acc=11902875802586231848#ApkPlace:p=com.openshift

Setup basic defaults for everything and uploaded our latest APK from build.phonegap.

Main things we need to discuss:
- Screenshots (I added 2 basic ones)
- Icon (I created a simple OSM icon as a placeholder)
- Decide when are we ready to launch Alpha testing

**Comment by ron-murhammer** [comment]
I created a final build for this first release for andriod in build.phonegap. I uploaded and completed all settings for the google play store. Andy please review everything and publish to Production: https://play.google.com/apps/publish/?dev_acc=11902875802586231848#ApkPlace:p=com.openshift

**Comment by sabre1041** [comment]
App has been published to Google Play store and is live!

https://play.google.com/store/apps/details?id=com.openshift

HUGE thank you to everyone on this major milestone for the project

**Comment by sabre1041** [comment]
@JaredBurck would you be able to add the Google Play icon to the site to the left of the PhoneGap icon and link to the following site:

https://play.google.com/store/apps/details?id=com.openshift
