### ISSUE TITLE
Create Publicly Available instance of OpenShift Enterprise 

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#50]
To validate integration with OpenShift Enterprise, create an publicly available instance of OpenShift Enterprise

Provide developers with url and credentials and any additional information necessary to integrate

**Comment by ghost** [comment]
Currently registration pages for Internal and Public are not allowing me to register, have opened a ticket with OS1 support.

**Comment by ghost** [comment]
Was able to successfully create a broker and node VM on OS1 public instance.  Will continue to work through configuring and will publish the public URL for the broker when finished

**Comment by ghost** [comment]
No longer blocked by subscription-manager issues. Was missing a certificate that is normally available when RHEL is installed

**Comment by ghost** [comment]
Can someone try to log in to the broker? I was able to but I'd like a second set of eyes (I was able to create a domain and a PHP app).  Currently, with the domain its kind of difficult to browse to the application, but I'll figure something out so we can demo apps we stand up.

https://209.132.179.194/console/applications
osm/opensource

**Comment by sabre1041** [comment]
logged in successfully!

**Comment by sabre1041** [comment]
do we want to configure the broker as a delegated subdomain.

ose.openshiftmobile.com?

**Comment by ghost** [comment]
I think that would be a good idea, much easier than trying to navigate to the public IP
