### ISSUE TITLE
Create GitHub Organization

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#54]
To separate the OpenShift Mobile project from an individual GitHub developer account and to add additional features, a GitHub Organization should be created and the existing project should be migrated.

GitHub organizations offer the following benefits
- Finer grained permission schemes
- All efforts related to the OpenShift Mobile project can live in a centralized space
- Additional forking functionality

**Comment by sabre1041** [comment]
openshift-mobile organization has already been registered. Contacted GitHub in attempt to determine owner and attempt transfer

**Comment by ghost** [comment]
I'll draft the email for requesting access

**Comment by sabre1041** [comment]
OpenShiftMobile organization created
