### ISSUE TITLE
Register and configure openshiftmobile.com

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#57]
Register the domain openshiftmobile.com and configure the following subdomains
- git.openshiftmobile.com - Pointing to this repository
- demo.openshiftmobile.com - Pointing to the nightly demo application

Update documentation to reflect the creation of domain and new subdomain of demo application

**Comment by jyore** [comment]
May be nice to:
- put up a home page at the root as a project home page
- add a docs.openshiftmobile.com for housing any formal documentation
- build.openshiftmobile.com for package downloads

**Comment by sabre1041** [comment]
Created the following subdomains which forwards to the following locations:
- demo.openshiftmobile.com -> http://demo-openshiftmobile.rhcloud.com/
  - Demo of OpenShift Mobile application which can be used by Ripple Emulator
- build.openshiftmobile.com - > https://build.phonegap.com/apps/796801/builds
  - PhoneGap Build
- git.openshiftmobile.com -> https://github.com/sabre1041/openshift-mobile/
  - GitHub repository

As for the hosting of the project homepage, considering we are leveraging GitHub extensively for both repository and issue tracking, we should probably look at GitHub pages to host content

**Comment by sabre1041** [comment]
The following have been configured:
- demo.openshiftmobile.com
- build.openshiftmobile.com
- git.openshiftmobile.com

**Comment by sabre1041** [comment]
Closing issue as primary goal has been completed. 

#69 accounts for the creation of a homepage
