### ISSUE TITLE
Create Gear with Git Repo

### ISSUE THREAD

**Issue by ghost** [openshift-mobile/openshift-mobile#61]
Add ability to spin up a gear and specify a git repo.

Usecase:
I want to demo an app/feature in a git repo/branch while away from my computer.

**Comment by sabre1041** [comment]
patch file representing commit to add functionality to use git repo as source when creating new application
- https://gist.github.com/sabre1041/9443277

Please review

**Comment by sabre1041** [comment]
Commit e65333c0b47e38a691aa6d78dc6e1e77f05cf4dc applied the functionality to specify a git source code base
