### ISSUE TITLE
Configure Email for openshiftmobile.com

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#63]
To provide both a central point of contact and to allow each core developer the ability to have a project related point of contact, configure the openshiftmobile.com domain with email functionality.

This can be leveraged through a number of services available today

**Comment by ghost** [comment]
Google apps is a solution. We can also use fastmail.fm which I use now.

**Comment by ghost** [comment]
I'll get google apps setup with email for the following accounts:
- andy, joey, eric, ron, zach
- mobile-dev
- "catcahll" that goes to andy

**Comment by ghost** [comment]
google apps is no longer free:
https://support.google.com/a/answer/2855120?hl=en

cost is $5 per user per month, so we're looking at least $25 per month

**Comment by jyore** [comment]
Really? I do not pay for mine....perhaps I got grandfathered in????

**Comment by ghost** [comment]
task is done via mail gun fwd'ing to individual accounts.  Will try and get round cube working to make it cleaner, but this should do the trick for now
