### ISSUE TITLE
Create OpenShift Mobile Logo

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#65]
Create a logo for the OpenShift Mobile application. This will provide a distinct brand for the application and allow the application to be featured in the various app stores

**Comment by ghost** [comment]
I'll take a stab at this

**Comment by ghost** [comment]
Ok, honest opinion guys (won't hurt my feelings), any of these work?  Like the idea?  Different direction?

Option 1
![phone logo preview - andriod](https://f.cloud.github.com/assets/208104/2492407/c912da1e-b22a-11e3-86d9-1bb0abb87843.png)
![phone logo preview - ios](https://f.cloud.github.com/assets/208104/2492415/0e9102c8-b22b-11e3-9ee2-f609c1c0cad4.png)

Option 2
![gears logo preview - android](https://f.cloud.github.com/assets/208104/2492405/c911aaea-b22a-11e3-8b76-ebaeef36dbd8.png)
![gears logo preview - ios](https://f.cloud.github.com/assets/208104/2492406/c912d884-b22a-11e3-8a0b-8b2b7dd9f24b.png)

Option 3
![gears hollow logo preview - ios](https://f.cloud.github.com/assets/208104/2492413/0e8ba10c-b22b-11e3-947c-5ab37817395a.png)
![gears hollow logo preview - andriod](https://f.cloud.github.com/assets/208104/2492414/0e90ab84-b22b-11e3-8be0-70a298a90557.png)

**Comment by ron-murhammer** [comment]
My vote is option 2

**Comment by jyore** [comment]
Honest opinion is I do not really get it or how it represents the app/app name. Also on the screen mockups, I do not know if I can distinguish what it is. 

My vote is a different direction

**Comment by ghost** [comment]
re: joey
I'll explore some other directions.  Let me know if you have any ideas/elements you'd like me to incorporate.

re: ron
did a quick iteration on the gear
![osm-app-logo---gears-11](https://f.cloud.github.com/assets/208104/2492486/2720838a-b231-11e3-835f-9c1d41ddd2c4.png)

**Comment by ghost** [comment]
More options.  This direction resonate with you guys at all:
Option 4
![gear list sample - ios](https://f.cloud.github.com/assets/208104/2492648/7d8d5908-b247-11e3-843b-cb1468aa2004.png)
![gear list2 sample - andriod](https://f.cloud.github.com/assets/208104/2492649/7d8d8040-b247-11e3-82c7-4fa076635e8b.png)

Option 5
![gear list2 sample - ios](https://f.cloud.github.com/assets/208104/2492650/7e7b4ef6-b247-11e3-9099-a2d400830133.png)
![gear list sample - andriod](https://f.cloud.github.com/assets/208104/2492651/7f04d1f8-b247-11e3-98e7-3181700d51a9.png)

**Comment by ghost** [comment]
One more.

Option 6:
![app icon sample - andriod](https://f.cloud.github.com/assets/208104/2492776/15fea8e8-b254-11e3-983b-bd2b3416f7a9.png)
![app icon sample - ios](https://f.cloud.github.com/assets/208104/2492777/15feb810-b254-11e3-9f06-2f35c1370527.png)

**Comment by sabre1041** [comment]
The concern I have for the most recent designs is that it looks a bit busy (wont be able to read the text). 

A suggestion I have could be as simple as modifying the option 3 to feature a cloud and two gears within?

**Comment by ghost** [comment]
I like that idea, a cloud with two gears in it. I don't think we need to imply in the icon that its mobile since it'll be on a mobile device.

**Comment by JaredBurck** [comment]
+1 for the idea of a cloud with two gears in it!

**Comment by ghost** [comment]
Gears in cloud:
![gears in cloud - ios](https://f.cloud.github.com/assets/208104/2493547/a8701ab8-b29a-11e3-9df5-bda8997e668c.png)
![gears in cloud - andriod](https://f.cloud.github.com/assets/208104/2493548/a8703476-b29a-11e3-9a08-9a2828017c3f.png)

I can also try and iteration with just an outline of the above elements and a single gradient (ala the iTunes logo on the iPhone screen grab).  Thoughts?

**Comment by JaredBurck** [comment]
looks good...maybe make the cloud outline thicker?

**Comment by ghost** [comment]
Thicker cloud outline, more centered gears:
![gears in cloud2 - ios](https://f.cloud.github.com/assets/208104/2493670/0af8510e-b2a1-11e3-9ee2-a1d17d73b581.png)
![gears in cloud2 - andriod](https://f.cloud.github.com/assets/208104/2493671/0af8bc0c-b2a1-11e3-99a0-0e8cf9885425.png)

**Comment by ron-murhammer** [comment]
I like the latest one. Might be nice to put a lighter gray gradient background instead of solid gray. Sort of like the camera icon has on the iphone one.

**Comment by JaredBurck** [comment]
yep...looks good to me

**Comment by ghost** [comment]
I like the feedback and direction.

A couple more comps:
Latest with Grey Gradient:
![gears in cloud3 - ios](https://f.cloud.github.com/assets/208104/2494045/1b61797c-b2b4-11e3-8b1c-1f10bab7d305.png)
![gears in cloud3 - andriod](https://f.cloud.github.com/assets/208104/2494046/1b62c55c-b2b4-11e3-9cdf-67d2214c96ff.png)

Same idea, white cloud with not fill, updated gears:
![gears in cloud4 - andriod](https://f.cloud.github.com/assets/208104/2494048/2141df08-b2b4-11e3-945b-bf097d84daeb.png)
![gears in cloud4 - ios](https://f.cloud.github.com/assets/208104/2494049/2148969a-b2b4-11e3-98db-354b72c012cc.png)

**Comment by sabre1041** [comment]
Great collaboration on this everyone. Like the new logo a lot. In favor of the while fill for the cloud instead of transparent

**Comment by jyore** [comment]
Looking better. I'd go white fill on cloud and a lighter gradient on the bg

**Comment by ghost** [comment]
Cool

Lighter start of the gradient?
End of the gradient?
Or both (overall basically)?

**Comment by jyore** [comment]
Both I think. Also maybe a touch of blue

**Comment by ghost** [comment]
slightly lighter gradient (top and bottom) plus a hint of blue:
![icon - lighter and blue - ios](https://f.cloud.github.com/assets/208104/2494485/ca3c781c-b2c7-11e3-9ea5-9f40bf7ae7e2.png)
![icon - lighter and blue - andriod](https://f.cloud.github.com/assets/208104/2494486/ca3fdb1a-b2c7-11e3-88a4-714e365cb657.png)

Keep going lighter?

**Comment by ghost** [comment]
I like how this one turned out

**Comment by jyore** [comment]
I would vote a bit lighter on the gradient, but its getting there. Good
work Zach

**Comment by ghost** [comment]
made the gradient lighter
![logo-lighter2 - ios](https://f.cloud.github.com/assets/208104/2507384/e3a6c11a-b3ba-11e3-91cf-7d3159e711f9.png)
![logo-lighter2 - andriod](https://f.cloud.github.com/assets/208104/2507385/e3a74e8c-b3ba-11e3-8580-72def6ba7c44.png)

**Comment by ghost** [comment]
Based on feedback assuming this is final logo for this release.
![logo---lighter2](https://f.cloud.github.com/assets/208104/2515559/d99e851a-b444-11e3-821a-0a2383f9eaeb.png)

Will generate the proper assets and send a pull request
