### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#66]
Update the README document for the repository to provide both developers and interested parties with essential information for becoming acquainted with the OpenShift Mobile project and provide links to additional content

**Comment by sabre1041** [comment]
Initial pass at updating the readme

https://github.com/sabre1041/openshift-mobile/blob/dc30165e21ac6e6233270e86e0bda7a31c8a0c8d/README.md

Let me know what you guys think (formatting of images will need some work)

**Comment by ghost** [comment]
proposed changes:

#Getting Started 
OpenShift Mobile is freely available on the Google Play store and iOS App Store
{icons}

-> 
{note the demotion to an h2}
##Download from the App Stores
The latest stable build of OpenShift Mobile is freely available on the Google Play store and iOS App Store
{icons}

# 

#Screen Shots -> ##Screen Shots

# 

#Contributing -> ##How to Contribute

**Comment by sabre1041** [comment]
Updated with the proposed changes

https://github.com/sabre1041/openshift-mobile/blob/42049fa61b31d3c8bf61f0c9a28f497cb6a4400f/README.md
