### ISSUE TITLE
Create Splashscreens

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#72]
Create splashscreens in the various supported formats. These splash screens should be  configured to be built using both the CLI and PhoneGap Build

**Comment by sabre1041** [comment]
@jyore, do you think the existing hardcoded splashscreen within the app can be removed?

**Comment by ghost** [comment]
Committed in #87 @sabre1041 is doing a smoke test locally, @ron-murhammer mind doing a smoke test on build to verify i didn't bust it?

**Comment by ghost** [comment]
Merged in #87
