### ISSUE TITLE
Dialog popup results in blank area in top left corner of screen

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#77]
When a dialog popup is presented in the application, the top left corner of the portion of the screen has blank content. The image below depicts the issue:

![screenshot_2014-03-24-15-46-58](https://f.cloud.github.com/assets/1191285/2507830/eb115756-b3c6-11e3-8fd2-f220ef2fb6d1.png)

**Comment by ron-murhammer** [comment]
Hey Andy,

I tested this in the Android simulator and don't see the issue when trying to delete domains or applications. Does this happen only on actual devices? If so which ones? What did you use to reproduce this issue?

Thanks,
Ron

**Comment by sabre1041** [comment]
Confirmed issue is isolated solely to Android hardware devices. 

After research, others are experiencing similar issues as noted in the following links:

http://stackoverflow.com/questions/18982521/jquery-mobile-global-popup-background

https://forum.jquery.com/topic/popup-overlay-on-android

Appears partially related to the _data-overlay-theme_' attribute on the popup. Removing the element does cause the bug to not occur

**Comment by ron-murhammer** [comment]
Since this is a jquery mobile issue, there isn't an easy fix so we are gonna de-scope this from this release and possibly revisit it in future releases.

**Comment by sabre1041** [comment]
Closing as no effort will continue on the OSE 2x side
