### ISSUE TITLE
Remove Splash Page from HTML

### ISSUE THREAD

**Issue by jyore** [openshift-mobile/openshift-mobile#80]
Phonegap inserts its own splash page, so having our own does not make sense.

**Comment by ron-murhammer** [comment]
Hey Joey. I believe you can override this. Here is the docs around it: http://docs.build.phonegap.com/en_US/3.1.0/configuring_icons_and_splash.md.html#Icons%20and%20Splash%20Screens

**Comment by jyore** [comment]
We could go that route, or leave the managed one and just remove the HTML
content as I did in the pull request #81

I think Andy and I were thinking more this route and update the image for
the spash screen that phonegap uses

**Comment by jyore** [comment]
closing as wontfix
