### ISSUE TITLE
App Creation w/ Embedded Cartridge Always Gives an Error

### ISSUE THREAD

**Issue by jyore** [openshift-mobile/openshift-mobile#88]
whenever I create an app with embedded cartridge I am presented an error regardless of success or failure of the creation of the app.

Perhaps this is because of the timeout on the REST call or something beyond our control? Definitely should be investigated, however.

**Comment by sabre1041** [comment]
Did experience these symptoms shortly after issue was opened. However, was able to create applications with embedded cartridges successfully a few hours later (OpenShift issue?)

@jyore can this issue be closed?

**Comment by sabre1041** [comment]
closing issue as not always reproducable
