### ISSUE TITLE
In WebApp Viewer, the backbutton always closes the viewer

### ISSUE THREAD

**Issue by jyore** [openshift-mobile/openshift-mobile#89]
When I click the back-button on android when inside the web view, the viewer closes instead of navigating backwards.

**Comment by sabre1041** [comment]
The backbutton appears to be a known issue with inappbrowser plugin.

When launching the browser, we pass in `location=no` to hide the location bar. This can be modified to give users the ability to use the browser navigation tools instead of the hardware backbutton

**Comment by jyore** [comment]
let's see if that will be helpful...also this may be required for iOS users
since there is no back button

**Comment by sabre1041** [comment]
@jyore please test to confirm functionality

**Comment by jyore** [comment]
Didn't we already do this? Worked fine on Android, which is why I approved
and merged the pull request. I do not have a way to test iOS devices
currently, so I cannot speak to that.

**Comment by sabre1041** [comment]
@rhoads-zach would you be able to test this functionality on your iOS device?
